name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - name: Build Project
        run: npm run build
        env:
          TURBO_TOKEN: NfCHREzLcqgSQ9bCKxcKIuwU
          TURBO_TEAM: thiagos-projects-a8c2a455

      - name: Deploy Storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
